import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "react-hot-toast";


const inter = Roboto({
  subsets: ["latin"],
  weight: "100"
});





export const metadata: Metadata = {
  title: "Music Hub ",
  description: "Generated by create next app",
  icons: {
    icon: "https://raw.githubusercontent.com/CodersHub-in/imageResources/c3a96233186c979e571accb2ede378430e4263e3/gust.svg",
  },
  applicationName: "Music Hub",
  authors: {
    name: "Swapnil Ingle",
    url: "https://github.com/codersHub-in",

  },

  creator: "Swapnil Ingle",
  publisher: "Swapnil Ingle",
  formatDetection: {
    telephone: true,
    address: true,
  },
  keywords: ["music", "music hub", "music player", "music player", "music player", "music player", "music player"],
  category: "music",


};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  console.log('children:')


  return (
    <html lang="en">

      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta name="google-adsense-account" content="ca-pub-1775178587078079" />
      <script
        async
        src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1775178587078079"
        crossOrigin="anonymous"
      ></script>
      <script async custom-element="amp-ad" src="https://cdn.ampproject.org/v0/amp-ad-0.1.js"></script>

      <AuthProvider>
        <body className={`${inter.className}  bg-black `}>

          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* <Navbar className="" /> */}
            {children}
            <Toaster position="bottom-center" containerClassName=" text-white" />
          </ThemeProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
